### ISSUE TITLE
Make dev mode take another acceptable port when the default is taken

### ISSUE THREAD

**Issue by lemonmade** [lemonmade/quilt#385]

**Comment by lemonmade** [comment]
```
Running step: Build GraphQL TypeScript definitions (Quilt.GraphQL.TypeScriptDefinitions)
Running step: Running app app in development mode (App.Develop)
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at Function.listen (/Users/lemon/dev/temporary/test-quilt/node_modules/express/lib/application.js:635:24)
    at Object.run (file:///Users/lemon/dev/temporary/test-quilt/node_modules/@quilted/craft/build/esm/plugins/app-develop.mjs:328:17)
    at async runStep (file:///Users/lemon/dev/temporary/test-quilt/node_modules/@quilted/craft/build/esm/cli/common.mjs:376:5)
    at async runNextStep (file:///Users/lemon/dev/temporary/test-quilt/node_modules/@quilted/craft/build/esm/cli/common.mjs:361:9)
    at async runStepsInStage (file:///Users/lemon/dev/temporary/test-quilt/node_modules/@quilted/craft/build/esm/cli/common.mjs:333:3)
    at async runStepsForTask (file:///Users/lemon/dev/temporary/test-quilt/node_modules/@quilted/craft/build/esm/cli/common.mjs:265:3)
    at async runDev (file:///Users/lemon/dev/temporary/test-quilt/node_modules/@quilted/craft/build/esm/cli/tasks/develop.mjs:14:3)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1399:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3000
}
```
